spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tuan0123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: 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
    from-email: tuanzebe21895@gmail.com

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123